# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-06-01 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintime',
            name='empid',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='logintime',
            name='intime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='logintime',
            name='outtime',
            field=models.TimeField(),
        ),
    ]
