# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-06-01 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200601_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintime',
            name='rdate',
            field=models.DateField(default=datetime.date(2020, 6, 1)),
        ),
    ]
