# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-06-01 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_logintime_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintime',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2020, 6, 1, 15, 53, 1, 650951, tzinfo=utc)),
        ),
    ]
