# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-06-04 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200603_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintime',
            name='io',
            field=models.CharField(default='I', max_length=1),
        ),
    ]
