# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-06-04 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_logintime_io'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintime',
            name='intime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='logintime',
            name='outtime',
            field=models.DateTimeField(),
        ),
    ]
